server.port=${SERVER_PORT:0}
server.servlet.context-path=/inventory-microservice
spring.application.name=inventory-microservice
spring.profiles.active=development

spring.cloud.config.uri=http://localhost:3333

eureka.instance.instance-id=${spring.application.name}:${UNIQUE_INSTANCE_ID:${random.value}}

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
